### ISSUE TITLE
Handle `APP_SIGNUP_ENABLED=true` setup with no working `MAIL_*` config

### ISSUE THREAD

**Issue by schu** [openmultiplechoice/openmultiplechoice#855]
If administrators have enabled user sign-up with `APP_SIGNUP_ENABLED=true` but don't have a working `MAIL_*` configuration, new users can register and the user will be created, but the backend will encounter an Internal server error on attempt to send the verification mail and consequently the new user doesn't have a way to verify their mail address (as they didn't receive a mail with a verification link).

```
[2024-05-02 18:18:29] production.ERROR: An email must have a "From" or a "Sender" header. {"exception":"[object] (Symfony\\Component\\Mime\\Exception\\LogicException(code: 0): An email must have a \"From\" or a \"Sender\" header. at /var/www/openmultiplechoice/vendor/symfony/mime/Message.php:138)
[stacktrace]
#0 /var/www/openmultiplechoice/vendor/symfony/mime/Email.php(414): Symfony\\Component\\Mime\\Message->ensureValidity()
#1 /var/www/openmultiplechoice/vendor/symfony/mailer/SentMessage.php(33): Symfony\\Component\\Mime\\Email->ensureValidity()
#2 /var/www/openmultiplechoice/vendor/symfony/mailer/Transport/AbstractTransport.php(68): Symfony\\Component\\Mailer\\SentMessage->__construct()
[...]
```

I'm undecided whether we should support installations without working mail setup (i.e. over a different flow for this scenario) or if we should expect it (we should document the requirement, then). I'm leaning towards the latter.

**Comment by levinuss** [comment]
> I'm undecided whether we should support installations without working mail setup (i.e. over a different flow for this scenario) or if we should expect it (we should document the requirement, then). I'm leaning towards the latter.

Also leaning towards the latter (not supporting it and documenting that requirement).
I think public signup should not be possible without a mail setup as other verification methods are complicated (to implement and work with).
IMHO a manual user creation by admins (to be implemented) could work without a mail setup and could be enough for small instances that do not have access to a mail server/provider.
